-- MySQL Script generated by MySQL Workbench
-- Mon Oct 27 20:38:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projet_memory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Projet_memory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projet_memory` DEFAULT CHARACTER SET utf8 ;
USE `Projet_memory` ;

-- -----------------------------------------------------
-- Table `Projet_memory`.`Equipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Equipe` (
  `id_equipe` INT NOT NULL AUTO_INCREMENT,
  `nom_equipe` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_equipe`),
  UNIQUE INDEX `nom_equipe_UNIQUE` (`nom_equipe` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Utilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Utilisateur` (
  `id_utilisateur` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_utilisateur` VARCHAR(50) NOT NULL,
  `prenom_utilisateur` VARCHAR(50) NOT NULL,
  `email_utilisateur` VARCHAR(100) NOT NULL,
  `mot_de_passe` VARCHAR(255) NOT NULL,
  `est_interne` TINYINT NOT NULL,
  `Equipe_id_equipe` INT NOT NULL,
  PRIMARY KEY (`id_utilisateur`),
  UNIQUE INDEX `Email_UNIQUE` (`email_utilisateur` ASC),
  INDEX `fk_Utilisateur_Equipe1_idx` (`Equipe_id_equipe` ASC),
  CONSTRAINT `fk_Utilisateur_Equipe1`
    FOREIGN KEY (`Equipe_id_equipe`)
    REFERENCES `Projet_memory`.`Equipe` (`id_equipe`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Projet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Projet` (
  `id_projet` INT(11) NOT NULL AUTO_INCREMENT,
  `titre_projet` VARCHAR(100) NOT NULL,
  `etat_projet` ENUM('Fini', 'En cours', 'Non commencée') NOT NULL,
  `description_projet` TEXT NOT NULL,
  `date_creation_projet` TIMESTAMP NOT NULL,
  `Utilisateur_id_utilisateur` INT(11) NOT NULL,
  PRIMARY KEY (`id_projet`),
  UNIQUE INDEX `titre_projet_UNIQUE` (`titre_projet` ASC),
  INDEX `fk_Projet_Utilisateur1_idx` (`Utilisateur_id_utilisateur` ASC),
  CONSTRAINT `fk_Projet_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Note`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Note` (
  `id_Note` INT(11) NOT NULL AUTO_INCREMENT,
  `titre_note` VARCHAR(100) NOT NULL,
  `etat_note` ENUM('Fini', 'En cours', 'Non commencée') NOT NULL,
  `description_note` TEXT NOT NULL,
  `date_creation_note` TIMESTAMP NOT NULL,
  `Utilisateur_id_utilisateur` INT(11) NOT NULL,
  `Projet_id_projet` INT(11) NOT NULL,
  PRIMARY KEY (`id_Note`),
  UNIQUE INDEX `titre_note_UNIQUE` (`titre_note` ASC),
  INDEX `fk_Note_Utilisateur1_idx` (`Utilisateur_id_utilisateur` ASC),
  INDEX `fk_Note_Projet1_idx` (`Projet_id_projet` ASC),
  CONSTRAINT `fk_Note_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_Projet1`
    FOREIGN KEY (`Projet_id_projet`)
    REFERENCES `Projet_memory`.`Projet` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Commentaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Commentaire` (
  `id_Commentaires` INT(11) NOT NULL AUTO_INCREMENT,
  `contenu_commentaire` TEXT NOT NULL,
  `date_commentaire` TIMESTAMP NOT NULL,
  `Utilisateur_id_utilisateur` INT(11) NOT NULL,
  `Note_id_Note` INT(11) NOT NULL,
  PRIMARY KEY (`id_Commentaires`),
  INDEX `fk_Commentaire_Utilisateur1_idx` (`Utilisateur_id_utilisateur` ASC),
  INDEX `fk_Commentaire_Note1_idx` (`Note_id_Note` ASC),
  CONSTRAINT `fk_Commentaire_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commentaire_Note1`
    FOREIGN KEY (`Note_id_Note`)
    REFERENCES `Projet_memory`.`Note` (`id_Note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Competence` (
  `id_Competence` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_competence` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_Competence`),
  UNIQUE INDEX `nom_competence_UNIQUE` (`nom_competence` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Couleur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Couleur` (
  `id_couleur` INT(11) NOT NULL AUTO_INCREMENT,
  `code_hexa` VARCHAR(7) NOT NULL,
  PRIMARY KEY (`id_couleur`),
  UNIQUE INDEX `code_hexa_UNIQUE` (`code_hexa` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Type_fichier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Type_fichier` (
  `id_type_fichier` INT NOT NULL AUTO_INCREMENT,
  `nom_type_fichier` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_type_fichier`),
  UNIQUE INDEX `nom_type_fichier_UNIQUE` (`nom_type_fichier` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Document`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Document` (
  `id_Document` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_fichier` VARCHAR(255) NOT NULL,
  `taille_fichier` INT(11) NOT NULL,
  `chemin_fichier` VARCHAR(500) NOT NULL,
  `date_ajout` TIMESTAMP NOT NULL,
  `Note_id_Note` INT(11) NOT NULL,
  `Type_fichier_id_type_fichier` INT NOT NULL,
  PRIMARY KEY (`id_Document`),
  INDEX `fk_Documents_Note_idx` (`Note_id_Note` ASC),
  INDEX `fk_Document_type_fichier1_idx` (`Type_fichier_id_type_fichier` ASC),
  CONSTRAINT `fk_Documents_Note`
    FOREIGN KEY (`Note_id_Note`)
    REFERENCES `Projet_memory`.`Note` (`id_Note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Document_type_fichier1`
    FOREIGN KEY (`Type_fichier_id_type_fichier`)
    REFERENCES `Projet_memory`.`Type_fichier` (`id_type_fichier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`NoteUtilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`NoteUtilisateur` (
  `Note_id_Note` INT(11) NOT NULL,
  `Utilisateur_id_Utilisateur` INT(11) NOT NULL,
  PRIMARY KEY (`Note_id_Note`, `Utilisateur_id_Utilisateur`),
  INDEX `fk_Note_has_Utilisateur_Utilisateur_idx` (`Utilisateur_id_Utilisateur` ASC),
  INDEX `fk_Note_has_Utilisateur_Note_idx` (`Note_id_Note` ASC),
  CONSTRAINT `fk_Note_has_Utilisateur_Note`
    FOREIGN KEY (`Note_id_Note`)
    REFERENCES `Projet_memory`.`Note` (`id_Note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Note_has_Utilisateur_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Notification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Notification` (
  `id_Notification` INT(11) NOT NULL AUTO_INCREMENT,
  `message` TINYTEXT NOT NULL,
  `date_notification` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id_Notification`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`ProjetUtilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`ProjetUtilisateur` (
  `Projet_id_Projet` INT(11) NOT NULL,
  `Utilisateur_id_Utilisateur` INT(11) NOT NULL,
  PRIMARY KEY (`Projet_id_Projet`, `Utilisateur_id_Utilisateur`),
  INDEX `fk_Projet_has_Utilisateur_Utilisateur_idx` (`Utilisateur_id_Utilisateur` ASC),
  INDEX `fk_Projet_has_Utilisateur_Projet_idx` (`Projet_id_Projet` ASC),
  CONSTRAINT `fk_Projet_has_Utilisateur_Projet`
    FOREIGN KEY (`Projet_id_Projet`)
    REFERENCES `Projet_memory`.`Projet` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projet_has_Utilisateur_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Role` (
  `id_role` INT(11) NOT NULL AUTO_INCREMENT,
  `nom_role` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_role`),
  UNIQUE INDEX `nom_role_UNIQUE` (`nom_role` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`RoleUtilisateur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`RoleUtilisateur` (
  `Role_id_Role` INT(11) NOT NULL,
  `Utilisateur_id_Utilisateur` INT(11) NOT NULL,
  PRIMARY KEY (`Role_id_Role`, `Utilisateur_id_Utilisateur`),
  INDEX `fk_Role_has_Utilisateur_Utilisateur_idx` (`Utilisateur_id_Utilisateur` ASC),
  INDEX `fk_Role_has_Utilisateur_Role_idx` (`Role_id_Role` ASC),
  CONSTRAINT `fk_Role_has_Utilisateur_Role`
    FOREIGN KEY (`Role_id_Role`)
    REFERENCES `Projet_memory`.`Role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Role_has_Utilisateur_Utilisateur`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Tag` (
  `id_tag` INT(11) NOT NULL AUTO_INCREMENT,
  `titre_tag` VARCHAR(55) NOT NULL,
  `Couleur_id_Couleur` INT(11) NOT NULL,
  `Utilisateur_id_Utilisateur` INT(11) NOT NULL,
  PRIMARY KEY (`id_tag`),
  UNIQUE INDEX `titre_UNIQUE` (`titre_tag` ASC),
  INDEX `fk_Tag_Couleur1_idx` (`Couleur_id_Couleur` ASC),
  INDEX `fk_Tag_Utilisateur1_idx` (`Utilisateur_id_Utilisateur` ASC),
  CONSTRAINT `fk_Tag_Couleur1`
    FOREIGN KEY (`Couleur_id_Couleur`)
    REFERENCES `Projet_memory`.`Couleur` (`id_couleur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`UtilisateurCompetence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`UtilisateurCompetence` (
  `Utilisateur_id_Utilisateur` INT(11) NOT NULL,
  `Competence_id_Competence` INT(11) NOT NULL,
  PRIMARY KEY (`Utilisateur_id_Utilisateur`, `Competence_id_Competence`),
  INDEX `fk_Utilisateur_has_Competences_Competences_idx` (`Competence_id_Competence` ASC),
  INDEX `fk_Utilisateur_has_Competences_Utilisateur_idx` (`Utilisateur_id_Utilisateur` ASC),
  CONSTRAINT `fk_Utilisateur_has_Competences_Competences`
    FOREIGN KEY (`Competence_id_Competence`)
    REFERENCES `Projet_memory`.`Competence` (`id_Competence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Competences_Utilisateur`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`UtilisateurNotification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`UtilisateurNotification` (
  `Utilisateur_id_Utilisateur` INT(11) NOT NULL,
  `Notification_id_Notification` INT(11) NOT NULL,
  `date_lecture` TIMESTAMP NOT NULL,
  PRIMARY KEY (`Utilisateur_id_Utilisateur`, `Notification_id_Notification`),
  INDEX `fk_Utilisateur_has_Notifications_Notifications_idx` (`Notification_id_Notification` ASC),
  INDEX `fk_Utilisateur_has_Notifications_Utilisateur_idx` (`Utilisateur_id_Utilisateur` ASC),
  CONSTRAINT `fk_Utilisateur_has_Notifications_Notifications1`
    FOREIGN KEY (`Notification_id_Notification`)
    REFERENCES `Projet_memory`.`Notification` (`id_Notification`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Notifications_Utilisateur`
    FOREIGN KEY (`Utilisateur_id_Utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`Tache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`Tache` (
  `id_tache` INT NOT NULL AUTO_INCREMENT,
  `titre_tache` VARCHAR(100) NOT NULL,
  `description_tache` TEXT NOT NULL,
  `etat_tache` ENUM('Fini', 'En cours', 'Non commencée') NOT NULL,
  `Projet_id_projet` INT(11) NOT NULL,
  PRIMARY KEY (`id_tache`),
  INDEX `fk_Tache_Projet1_idx` (`Projet_id_projet` ASC),
  UNIQUE INDEX `titre_tache_UNIQUE` (`titre_tache` ASC),
  CONSTRAINT `fk_Tache_Projet1`
    FOREIGN KEY (`Projet_id_projet`)
    REFERENCES `Projet_memory`.`Projet` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_memory`.`UtilisateurTache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`UtilisateurTache` (
  `Utilisateur_id_utilisateur` INT(11) NOT NULL,
  `Tache_id_tache` INT NOT NULL,
  PRIMARY KEY (`Utilisateur_id_utilisateur`, `Tache_id_tache`),
  INDEX `fk_Utilisateur_has_Tache_Tache1_idx` (`Tache_id_tache` ASC),
  INDEX `fk_Utilisateur_has_Tache_Utilisateur1_idx` (`Utilisateur_id_utilisateur` ASC),
  CONSTRAINT `fk_Utilisateur_has_Tache_Utilisateur1`
    FOREIGN KEY (`Utilisateur_id_utilisateur`)
    REFERENCES `Projet_memory`.`Utilisateur` (`id_utilisateur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Utilisateur_has_Tache_Tache1`
    FOREIGN KEY (`Tache_id_tache`)
    REFERENCES `Projet_memory`.`Tache` (`id_tache`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`ProjetTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`ProjetTag` (
  `Projet_id_projet` INT(11) NOT NULL,
  `Tag_id_tag` INT(11) NOT NULL,
  PRIMARY KEY (`Projet_id_projet`, `Tag_id_tag`),
  INDEX `fk_Projet_has_Tag_Tag1_idx` (`Tag_id_tag` ASC),
  INDEX `fk_Projet_has_Tag_Projet1_idx` (`Projet_id_projet` ASC),
  CONSTRAINT `fk_Projet_has_Tag_Projet1`
    FOREIGN KEY (`Projet_id_projet`)
    REFERENCES `Projet_memory`.`Projet` (`id_projet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Projet_has_Tag_Tag1`
    FOREIGN KEY (`Tag_id_tag`)
    REFERENCES `Projet_memory`.`Tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Projet_memory`.`TagNote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Projet_memory`.`TagNote` (
  `Tag_id_tag` INT(11) NOT NULL,
  `Note_id_Note` INT(11) NOT NULL,
  PRIMARY KEY (`Tag_id_tag`, `Note_id_Note`),
  INDEX `fk_Tag_has_Note_Note1_idx` (`Note_id_Note` ASC),
  INDEX `fk_Tag_has_Note_Tag1_idx` (`Tag_id_tag` ASC),
  CONSTRAINT `fk_Tag_has_Note_Tag1`
    FOREIGN KEY (`Tag_id_tag`)
    REFERENCES `Projet_memory`.`Tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tag_has_Note_Note1`
    FOREIGN KEY (`Note_id_Note`)
    REFERENCES `Projet_memory`.`Note` (`id_Note`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
